### ISSUE TITLE
need to support allow_ingest_behind

### ISSUE THREAD

**Issue by chrislusf** [tecbot/gorocksdb#113]
https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files#ingestion-behind

This is needed to use with IngestExternalFile(), which is added in https://github.com/tecbot/gorocksdb/pull/91.

https://github.com/facebook/rocksdb/blob/521b4c28b9a5bead921a1d1a475495bae2ccbea1/docs/_posts/2017-06-29-rocksdb-5-5-1-released.markdown

**Comment by chrislusf** [comment]
@zhenkai could you please help here?

**Comment by kapitan-k** [comment]
@chrislusf just added a pull request https://github.com/facebook/rocksdb/pull/3151 for the corresponding c wrapper to allow ingest_behind, once accepted I could commit:

// SetIngestBehind set to true results in duplicate keys in the file being ingested
// to be skipped rather than overwriting existing data under that key.
// Usecase: back-fill of some historical data in the database without
// over-writing existing newer version of data.
// This option could only be used if the DB has been running
// with allow_ingest_behind=true since the dawn of time.
// All files will be ingested at the bottommost level with seqno=0.
func (opts *IngestExternalFileOptions) SetIngestBehind(flag bool) {
	C.rocksdb_ingestexternalfileoptions_set_ingest_behind(opts.c, boolToChar(flag))
}
